stages:
  - test
  - build
  - deploy

variables:
  LINO_LATEST_IMAGE: $DOCKER_USER/webcrawler:latest
  CRONJOB_LATEST_IMAGE: $DOCKER_USER/cronjob-webcrawler-ru:latest

##############################################################################
#                                 Test stage                                 #
##############################################################################

test_flake8:
  image: ejplatform/python:alpine
  stage: test
  script:
    - flake8

services:
  - mongo:latest

unit_test:
  image: python:3.6
  stage: test
  variables:
    DB_URI: 'mongodb://mongo/ru'
  before_script:
    - pip install -r requirements.txt
    - apt-get update
    - apt-get upgrade -y
    - apt-get install default-jdk -y
    - chmod +x install-poppler.sh
    - ./install-poppler.sh
    - cd crawler
  script:
    - pytest


##############################################################################
#                                 Build stage                                #
##############################################################################

build webcrawler:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
  script:
    - docker build -t $LINO_LATEST_IMAGE .
    - docker push $LINO_LATEST_IMAGE
  only:
    - /master/
  environment: production

build cronjob:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
  script:
    - docker build -t $CRONJOB_LATEST_IMAGE .
    - docker push $CRONJOB_LATEST_IMAGE
  only:
    - /master/


##############################################################################
#                                 Deploy stage                               #
##############################################################################

deploy webcrawler production:
  image: cdrx/rancher-gitlab-deploy
  stage: deploy
  script:
    - "upgrade
            --service webcrawler-lino
            --environment $RANCHER_ENVIRONMENT
            --stack $RANCHER_STACK
            --rancher-key $RANCHER_ACCESS_KEY
            --rancher-secret $RANCHER_SECRET_KEY
            --rancher-url $RANCHER_URL"
  only:
    - /master/

deploy cronjob production:
  image: cdrx/rancher-gitlab-deploy
  stage: deploy
  script:
    - "upgrade
            --service cronjob-webcrawler-ru
            --environment $RANCHER_ENVIRONMENT
            --stack $RANCHER_STACK
            --rancher-key $RANCHER_ACCESS_KEY
            --rancher-secret $RANCHER_SECRET_KEY
            --rancher-url $RANCHER_URL"
  only:
    - /master/
