version: '3'

services:
  server-crawler:
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/Lino-WebCrawler
    depends_on:
      - mongo-ru

  mongo-ru:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - /l/crawler/menu_db:/data/db