version: '3'

services:
  server-crawler:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - .:/Lino-WebCrawler
    depends_on:
      - mongo-ru
    environment:
      - DB_URI=mongodb://mongo-ru/ru
    tty: true
    stdin_open: true

  mongo-ru:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - /l/crawler/menu_db:/data/db
